blog/urls.py
from django.contrib import admin
from django.urls import path, include
from forum.api_views import api_ninja

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path("auth_officers/", include('user_officers.urls', namespace="auth_officers")),
    path("captcha/", include("captcha.urls")),
    path("api_ninja/", api_ninja.urls)
]

forum/urls.py
from django.urls import path
from .views import (home, make_order_for_private, list_of_all_orders, create_news_of_british_army, watching_news_of_british_army,
                    add_news_to_check_bucket, bucket_check_view, news_by_detail)


app_name = 'forum'

urlpatterns = [
    path('home-page/', home, name='home_page' ),
    path('make-order-for-soldier/', make_order_for_private, name='make_order_for_soldier'),
    path('list-of-all-orders/', list_of_all_orders, name='list_of_all_orders'),
    path('create-news-of-british-army/', create_news_of_british_army, name='create_news_of_british_army'),
    path('watching-news-of-british-army/', watching_news_of_british_army, name='watching_news_of_british_army'),
    path('watching-news-of-british-army/<int:news_id>/', news_by_detail, name='news_by_detail'),
    path('watching-news-of-british-army/add_news_to_check_bucket/<int:news_id>/', add_news_to_check_bucket, name='add_news_to_check_bucket'),
    path('bucket-check-view/', bucket_check_view, name='bucket_check_view')
]

forum/models.py
import datetime
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import TextField
from django.conf import settings
from django.utils import timezone

class Order(models.Model):
    name_order = models.CharField()
    description_of_order = models.TextField()
    rate_for_order = models.IntegerField(default=1, validators=[MinValueValidator(0), MaxValueValidator(10)])
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='order',
        null=True,
        blank=True
    )
    data_giving = models.DateTimeField()

    def __str__(self):
        return F"{self.name_order} {self.user} {self.data_giving}"

class News(models.Model):
    news_name = models.CharField()
    description_of_news = models.TextField()
    rate_for_news = models.IntegerField(default=1, validators=[MinValueValidator(0), MaxValueValidator(10)])
    published_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='news',
        null=True,
        blank=True
    )
    data_giving = models.DateTimeField(default=timezone.now)



class BusketCheck(models.Model):

    STATUS = [
        ("NAPR", "Not Approved"),
        ("APR", "Approved"),
        ("NLN", "In line"),
        ("NCHKY", "not checked yet"),
        ("CHKN", "Is checking now")
    ]

    published_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='user',
        null=True,
        blank=True
    )
    check_info_news = models.ForeignKey(
        News,
        on_delete=models.CASCADE,
        related_name='news',
        null=True,
        blank=True
    )
    status = models.CharField(choices=STATUS, default="NCHKY")

forum/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Order, News



class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ("name_order", "description_of_order", "data_giving", "rate_for_order", "user")

    def save(self, commit=True):
        order = super().save(commit=False)
        order.is_active = True
        order.save()
        return order




class NewsForm(forms.ModelForm):

    captcha = CaptchaField(label="Tap a code from the picture")

    class Meta:
        model = News
        fields = ("news_name", "description_of_news", "rate_for_news", "data_giving")

    def save(self, commit=True):
        news = super().save(commit=False)
        news.is_active = True
        news.save()
        return news

forum/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.core.cache import cache

from .forms import OrderForm, NewsForm
from .models import Order, News, BusketCheck
from .filters import PrivateFilter
import logging


logger = logging.getLogger(__name__)


def home(request):
    order_list = Order.objects.all()
    paginator = Paginator(order_list , 1)
    page_number = request.GET.get('page', 1)
    try:
        orders = paginator.page(page_number)
    except EmptyPage:
        orders = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        orders = paginator.page(1)
    return render(request, 'forum/home.html', {'orders': orders})

@login_required
def make_order_for_private(request):

    if not request.user.staff_for_create():
        return HttpResponseForbidden("You don't have permission to create orders.")

    form = OrderForm()

    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            material = form.save(commit=False)
            material.save()
            messages.success(request, "Order has been added")
            return redirect("forum:make_order_for_soldier")
    return render(request, 'forum/make_order_for_recruit.html', {'form': form})

def list_of_all_orders(request):
    orders = Order.objects.all()
    return render(request,'forum/all_order_view.html', {'orders': orders} )



@login_required
def create_news_of_british_army(request):

    if not request.user.can_create_news():
        return HttpResponseForbidden("You don't have permission to create news.")

    form = NewsForm()

    if request.method == "POST":
        form = NewsForm(request.POST)
        if form.is_valid():
            news = form.save(commit=False)
            news.published_by = request.user
            news.save()
            messages.success(request, "The layer of magazine news has been added")
            return redirect("forum:watching_news_of_british_army")
    return render(request, 'forum/create_news_of_british_army.html', {'form': form})

def watching_news_of_british_army(request):
    cache_key = "news_list"
    news = cache.get(cache_key)

    if not news:
        logger.warning("Bases from BD")
        news = News.objects.all()
        cache.set(cache_key, news, timeout=300)
    else:
        logger.warning("Bases from Cache")
    return render(request,'forum/all_news.html', {'news': news})

def news_by_detail(request, news_id):
    news = get_object_or_404(News, id=news_id)
    return render(request,'forum/news_by_detail.html', {'news': news})

@login_required
def add_news_to_check_bucket(request, news_id):

    if not request.user.staff_for_create():
        return HttpResponseForbidden("You don't have permission to this action")

    news = News.objects.get(id=news_id)
    BusketCheck.objects.create(check_info_news=news, published_by=request.user)
    messages.success(request, "The object news's was added to check bucket")
    return redirect("forum:watching_news_of_british_army")


@login_required
def bucket_check_view(request):
    news = BusketCheck.objects.filter(published_by=request.user).select_related("check_info_news")
    return render(request, 'forum/bucket.html', {'news': news})

forum/templates/forum/all_news.html
{% extends 'base.html' %}

{% block title %}LIVE NEWS OF BA{% endblock %}

{% block content %}
{% for new in news %}
<div class="container px-4 px-lg-5 mt-5">
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ new.news_name }}</h5>
            <p class="card-text">{{ new.description_of_news }}</p>
            <p class="card-text">Rate: {{ new.rate_for_news }}</p>
            <p class="card-text">By: {{ new.published_by }}</p>
            <p class="card-text">Date: {{ new.data_giving }}</p>
        </div>
        <div><a href="{% url 'forum:news_by_detail' new.id %}">More Details right about the news right here</a></div>
        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
                <a class="btn btn-outline-primary mt-auto" href="add_news_to_check_bucket/{{new.id}}">For Checking</a>
            </div>
        </div>
    </div>
</div>
{% empty %}
<div class="alert alert-info">
    No news has been published yet.
</div>
{% endfor %}
{% endblock %}

forum/templates/forum/all_order_view.html
{% extends 'base.html' %}

{% block title %}View All Recruits{% endblock %}
{% block content %}
{% for order in orders %}
<div class="container w-50">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ order.name_order }}</h5>
            <p class="card-text">{{ order.description_of_order }}</p>
            <p class="card-text">{{ order.rate_for_order }}</p>
            <p class="card-text">{{ order.rank }}</p>
            <p class="card-text">{{ order.user.first_name }}</p>
            <p class="card-text">{{ order.data_giving }}</p>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

forum/templates/forum/bucket.html
{% extends "base.html" %}

{% block content %}
<h2>Your Check Bucket list</h2>

{% if news %}
<table class="table">
    <thead>
        <tr>
            <th>Objects</th>
            <th>info news</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
        {% for item in news %}

        <tr
            {% if item.status == "NCHKY" %}
                class="table-warning"
            {% elif item.status == "NLN" %}
                class="table-success"
            {% endif %}
        >
            <td>{{ item.check_info_news.news_name }}</td>
            <td>{{ item.check_info_news.description_of_news }} $</td>

            <td>

                {% if item.status == "NLN" %}
                    <span class="badge bg-warning text-dark">
                        In the line
                    </span>

                {% elif item.status == "APR" %}
                    <span class="badge bg-success">
                        Approved the info
                    </span>

                {% elif item.status == "NAPR" %}
                    <span class="badge bg-success">
                        Not Approved the info
                    </span>

                {% elif item.status == "NCHKY" %}
                    <span class="badge bg-success">
                        Not yet , wait for free line
                    </span>

                {% elif item.status == "CHKN" %}
                    <span class="badge bg-success">
                        Now is checking
                    </span>
                {% endif %}
            </td>
        </tr>

        {% endfor %}
    </tbody>
</table>
{% else %}
<p>The bucket is empty</p>
{% endif %}

{% endblock %}

forum/templates/forum/create_news_of_british_army.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container w-50">
    <h2>Create the for private the order</h2>
    {% if user.can_create_news %}
    <form method="post" action="{% url 'forum:create_news_of_british_army' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
    {% else %}
    <div class="alert alert-danger">
        You do not have permission to add news of BA.
    </div>
    {% endif %}
    {% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    </form>
</div>
{% endblock %}

forum/templates/forum/home.html
{% extends 'base.html' %}

{% block content %}
{% for private in privates %}
<div class="container w-50">
    <div class="card">
        <div class="card-header">
            {{ private.call_sign }}
        </div>
        <div class="card-body">
            <a href="{% url 'forum:private_view' private.id %}" class= "btn btn-primary">Read  full biography private: {{ private.call_sign }}</a>
        </div>
    </div>
</div>
{% endfor %}

<div class="pagination d-flex justify-content-center mt-4">
    <ul class="pagination">
        {% if privates.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ private.previous_page_number }}"
            >Back</a
            >
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Back</span>
        </li>
        {% endif %}

        {% for num in private.paginator.page_range %}
        <li class="page-item {% if num == private.number %}active{% endif %}">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endfor %}

        {% if private.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ privates.next_page_number }}"
            >Move</a
            >
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Move</span>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

forum/templates/forum/make_order_for_recruit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container w-50">
    <h2>Create the for private the order</h2>
    {% if user.can_create_orders %}
    <form method="post" action="{% url 'forum:make_order_for_soldier' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
    {% else %}
    <div class="alert alert-danger">
        You do not have permission to create orders.
    </div>
    {% endif %}
    {% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    </form>
</div>
{% endblock %}

forum/templates/forum/news_by_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container px-4 px-lg-5 mt-5">
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ news.news_name }}</h5>
            <p class="card-text">{{ news.description_of_news }}</p>
            <p class="card-text">Rate: {{ news.rate_for_news }}</p>
            <p class="card-text">By: {{ news.published_by.last_name }}</p>
            <p class="card-text">Date: {{ news.data_giving }}</p>
        </div>
    </div>
</div>
{% endblock %}