blog/urls.py
from django.contrib import admin
from django.urls import path, include
from forum.api_views import api_ninja

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path("auth_officers/", include('user_officers.urls', namespace="auth_officers")),
    path("captcha/", include("captcha.urls")),
    path("api_ninja/", api_ninja.urls)
]

forum/urls.py
from django.urls import path
from .views import (home, make_order_for_private, list_of_all_orders, create_news_of_british_army, watching_news_of_british_army,
                    add_news_to_check_bucket, bucket_check_view, news_by_detail)


app_name = 'forum'

urlpatterns = [
    path('home-page/', home, name='home_page' ),
    path('make-order-for-soldier/', make_order_for_private, name='make_order_for_soldier'),
    path('list-of-all-orders/', list_of_all_orders, name='list_of_all_orders'),
    path('create-news-of-british-army/', create_news_of_british_army, name='create_news_of_british_army'),
    path('watching-news-of-british-army/', watching_news_of_british_army, name='watching_news_of_british_army'),
    path('watching-news-of-british-army/<int:news_id>/', news_by_detail, name='news_by_detail'),
    path('watching-news-of-british-army/add_news_to_check_bucket/<int:news_id>/', add_news_to_check_bucket, name='add_news_to_check_bucket'),
    path('bucket-check-view/', bucket_check_view, name='bucket_check_view')
]

user_officers/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import register_view, profile_view


app_name = 'auth_officers'


urlpatterns = [
    path('register-page/', register_view, name='register_view'),
    path("profile/", profile_view, name="profile"),
    path("login/", LoginView.as_view(template_name="user_officers/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout")
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>British Army</title>
</head>
<body>
{% if messages %}
<div class="container mt-3">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>
{% endif %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand bold" href="{% url 'forum:home_page' %}">
            <img src="https://flagcdn.com/gb.svg" alt="UK Flag" width="30" height="30">British Army
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'forum:home_page' %}">Home</a>
                </li>
                {% if user.staff_for_create %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum:list_of_all_orders' %}">View Order</a>
                </li>
                {% endif %}
                <li class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        Dropdown button
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'forum:watching_news_of_british_army' %}">News of
                            BA</a></li>
                        {% if user.role == "PRESS" %}
                        <li><a class="dropdown-item" href="{% url 'forum:create_news_of_british_army' %}">Create the
                            news</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link position-relative" href="{% url 'forum:bucket_check_view' %}">
                        🗒 Check Bucket
                    </a>
                </li>
                <span class="navbar-text ms-auto">
				{% if request.user.is_authenticated %}
				<a href="{% url 'auth_officers:profile' %}">Profile</a>
				{% else %}
				<a href="{% url 'auth_officers:register_view' %}">Register</a>
				<a class="ms-3" href="{% url 'auth_officers:login' %}">Login</a>
				{% endif %}
			</span>
                {% if request.user.is_authenticated %}
                <form method="post" action="{% url 'auth_officers:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="dropdown-item text-danger ms-3">Log out</button>
                    {% endif %}
                </form>
            </ul>
        </div>
    </div>
</nav>

<div class="container mt-4">
    {% block content %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>